### ISSUE TITLE
Gstreamer "qtimlesnpe" element not found.

### ISSUE THREAD

**Issue by veeramallirajesh** [quic/sample-apps-for-robotics-platforms#17]
Hello,

I am trying to build a Gstreamer application for image segmentation on the camera stream data. For this, we need the "qtimlesnpe" GStreamer element. From one of the Qualcomm forums, I know that this element is not yet released. Could you please let me know by when this element is planned to be released and could you provide some example application with this element so that we are not restricted to work only with one machine learning framework i.e. TFLite? Thank you.
link to the forum: https://developer.qualcomm.com/forum/qdn-forums/hardware/qualcomm-robotics-rb5-development-kit/68177

Regards
Rajesh

**Comment by wanghaow** [comment]
Hi Rajesh,

We will update this plugin in a later release.

Thanks

**Comment by veeramallirajesh** [comment]
Is there any timeline for that? It would be helpful to know. Thank you.

**Comment by veeramallirajesh** [comment]
Is there any update on this? Could you please let me know? Thank you.

**Comment by sahilbm** [comment]
@veeramallirajesh,

Please take a look into this in order to build the plugin,
https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/gst_mle_oss/gst_snpe

**Comment by quic-sbudha** [comment]
Hi @veeramallirajesh 

You can follow "https://docs.qualcomm.com/bundle/publicresource/topics/80-88500-3/72_Install_qtimlsnpe_GStreamer_plug_in_.html" to build qtimlsnpe plugin for QRB5165 LU 2.0

Thanks,
Sumith
