### ISSUE TITLE
Compiling Tflite w/ NNAPI and Hexagon DSP Support

### ISSUE THREAD

**Issue by mrawding** [quic/sample-apps-for-robotics-platforms#51]
Hello,

I am trying to install tensorflow lite on an EVT RB5 board. 

The software reference guide here:

 https://developer.qualcomm.com/qualcomm-robotics-rb5-kit/software-reference-manual/machine-learning/tensorflow

Says that NNAPI and DSP Delegate supports in Tflite are supported. However, I am unable to compile tensorflow lite with NNAPI enabled because the image is missing the android ndk libraries that are required. What packages/sdks do I neUed to install to build this correctly.

I found that my system is missing preproccesor defiinition: ```__ANDROID___``` which causes tflite to build correctly but disable NNAPI.

After forcing that definition it is missing headers and libraries like ```android/api-level.h ```

Is this something that is still in the works? Or am I missing something. I see that the hexagon sdk has the relevant android ndk tool chain, but I do not know of instructions on how to build the android sdk and install on the RB5.

Also after installing the snpe toolkit and running the runtime validator only GPU prerequisites are present.

I would really appreciate an update on this issue or a push in the right direction! Thank you.

**Comment by St190706025** [comment]
Which tensorflow version that you use it?

**Comment by quic-sbudha** [comment]
Hi @mrawding ,

**TensorFlow Lite:**

TensorFlow Lite (v2.x) is part of the platform source code, for execution of models in the Qualcomm® platform.

You can follow "https://docs.qualcomm.com/bundle/publicresource/topics/80-88500-4/146_TensorFlow_Lite.html" to test tflite model.

**platform-validator:**

 1. Download latest SNPE from Qualcomm®
 2. Run the following commands on QRB5165 for SNPE 2.10+:
>      adb root
>      adb shell
>      export SNPE_ROOT=<Path to SNPE> # Replace with extracted SNPE folder path
>      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${SNPE_ROOT}/lib/aarch64-ubuntu-gcc7.5/
>      export PATH=$PATH:${SNPE_ROOT}/bin/aarch64-ubuntu-gcc7.5/
>      export ADSP_LIBRARY_PATH="${SNPE_ROOT}/lib/hexagon-v66/unsigned/;/usr/lib/rfsa/adsp;/dsp"
>      chmod +x ${SNPE_ROOT}/bin/aarch64-ubuntu-gcc7.5/snpe-platform-validator

3.  Make sure "**libCalculator_skel.so**" and "**libSnpeDspV66Skel.so**" libraries are at "${SNPE_ROOT}/lib/hexagon-v66/unsigned/"
4.  snpe-platform-validator --runtime dsp




Thanks,
Sumith
