### ISSUE TITLE
Gst Streamer applications. 

### ISSUE THREAD

**Issue by dac31415** [quic/sample-apps-for-robotics-platforms#63]
Hello, 

How can I open/display the isp camera or gui (Gstreamer applications) while using LU image? I followed thundercomm guide to have LU desktop version (gnome) so I had to dissble Weston Client.

**Comment by mayur-mk** [comment]
Hi @dac31415, 

You can run [weston.sh](https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/gst-python-samples/Gstreamer-Applications) for display output. 
You won't need to disable Weston client.
for isp camera display output you can run the following script 
https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/blob/master/gst-python-samples/Gstreamer-Applications/gst_camera/ispcam_display.py 
or 
https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/blob/master/Gstreamer-Applications/gst_camera/ispcam_display.c

Once you run the above script you can able to see the isp camera output on your screen.

Thanks & regards, 
Mayur

**Comment by quic-sbudha** [comment]
Hi @dac31415 

You can execute the below commands to display ispcam 
`./weston.sh`
`python sample-apps-for-robotics-platforms/RB5/linux_kernel_4_x/GStreamer-apps/python/gst_camera/ispcam_display.py 0`

Thanks,
Sumith
