### ISSUE TITLE
gst_snpe wrong output

### ISSUE THREAD

**Issue by RalphMao** [quic/sample-apps-for-robotics-platforms#64]
We are trying to build the gst plugin with SNPE 1.61, and we notice that the output is incorrect (fp32 range from -1e38 to 1e38). I saw your comments on https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/gst_mle_oss/gst_snpe that " The current version of SNPE v1.48 causes issues. Revert to v1.43". 

Could you provide more details on the problem that you encountered? Thank you!
@adpandit

**Comment by bmallem** [comment]
@RalphMao, How are you verifying the outputs from gst_snpe? If you are saving gst_snpe outputs to a file and reading using other modules such as numpy, please check the endianness when reading the outputs.

**Comment by quic-sbudha** [comment]
Hi @RalphMao 

Let us know if you are still facing this issue with latest SNPE release ? If yes, then do share steps/snippet on how you are validating the output.

Thanks,
Sumith

**Comment by quic-sbudha** [comment]
Hi @RalphMao 

Closing this issue.
You can re-open this, if you still face any issue with latest release.

Thanks,
Sumith
