### ISSUE TITLE
Unable to Install  apt-get install libgstreamer1.0-dev and other

### ISSUE THREAD

**Issue by krissree** [quic/sample-apps-for-robotics-platforms#65]
apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstr
eamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gst
reamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-
doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreame
r1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
/bin/sh: apt-get: not found

**Comment by quic-sbudha** [comment]
Hi @krissree ,

1. Check with "apt" instead of "apt-get"
2. This issue is on QRB5165 LE or UBUNTU?

Thanks,
Sumith

**Comment by quic-khrahul** [comment]
Hi @krissree,

LU build support apt-get install. LE build apt-get is not supported. 
Please let us know if you still face any issue.

Thanks,
Rahul
