### ISSUE TITLE
how to enable apt packages on android version? 

### ISSUE THREAD

**Issue by jishang1602** [quic/sample-apps-for-robotics-platforms#97]
how to enable apt packages on android version?

**Comment by quic-sbudha** [comment]
Hi @jishang1602,

Qualcomm® Robotics development kits supports two types of Linux based operating system images. First is the “LE” version, second is the “UBUN” version

1. Qualcomm® Robotics RB5 dev kit
2. Qualcomm® Robotics RB1 and RB2 dev kits

For android, you can follow "https://github.com/quic/ai-stack-models/tree/main/ai-solutions/android"

Thanks,
Sumith
