### ISSUE TITLE
Unable to deploy Qualcomm® Neural Processing SDK libraries on target device

### ISSUE THREAD

**Issue by ManuAPPU** [quic/sample-apps-for-robotics-platforms#98]
Hi , i am trying to run Ai vision solution using yolov5, but i am unable to reproduce steps in readme beacuse in websites the available version of Neural Processing SDK libraries on target device is 2.10+ but in readme its snpe 1.68 , can you please update readme for newer versions.

**Comment by quic-sbudha** [comment]
Hi @ManuAPPU 

For latest SNPE release you can use below commands
```
cd <SNPE_ROOT>
adb root
adb push lib\aarch64-ubuntu-gcc7.5\.  /usr/lib/
adb push bin\aarch64-ubuntu-gcc7.5\snpe-net-run  /usr/bin/
adb push lib\hexagon-v66\unsigned\.  /usr/lib/rfsa/adsp/

```
```
adb shell
chmod +x /usr/bin/snpe-net-run
snpe-net-run --version
```

Thanks,
Sumith

**Comment by ManuAPPU** [comment]
Hi Thank you for updating this i just done these steps and tried to make a Ai Vision solution application, but got error like this

root@qrb5165-rb5:~/sample-apps-for-robotics-platforms/RB5/linux_kernel_5_x/AI-ML-apps/AI_Vision_Solutions/build# make
Scanning dependencies of target main
[ 11%] Building CXX object src/CMakeFiles/main.dir/Configuration.cpp.o
[ 22%] Building CXX object src/CMakeFiles/main.dir/DecodeQueue.cpp.o
[ 33%] Building CXX object src/CMakeFiles/main.dir/ModelInference.cpp.o
In file included from /root/sample-apps-for-robotics-platforms/RB5/linux_kernel_5_x/AI-ML-apps/AI_Vision_Solutions/src/../inc/YOLOv5Snpe.h:9,
                 from /root/sample-apps-for-robotics-platforms/RB5/linux_kernel_5_x/AI-ML-apps/AI_Vision_Solutions/src/ModelInference.cpp:3:
/root/sample-apps-for-robotics-platforms/RB5/linux_kernel_5_x/AI-ML-apps/AI_Vision_Solutions/src/../inc/SNPERuntime.h:10:10: fatal error: SNPE/SNPE.hpp: No such file or directory
   10 | #include "SNPE/SNPE.hpp"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/main.dir/build.make:89: src/CMakeFiles/main.dir/ModelInference.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:94: src/CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
